### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by NadiaKhatib** [FACG4/RIAA#24]
Good job (Write code - write notes)
But you should take into consideration that there are spaces in the code to be structured code

**Comment by ashatat** [comment]
Thanks for your review :+1: 
we'd much like it if you can give us some tips about (writing notes?)

**Comment by NadiaKhatib** [comment]
I mean a Good job for Wrote Notes in your Code.
And[ here]( https://www.cs.utah.edu/~germain/PPS/Topics/commenting.html )useful link to write a note

**Comment by ashatat** [comment]
@NadiaKhatib  Thanks so much
