### ISSUE TITLE
queries.css

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG4/RIAA#26]
I like the fact that you put your queries in a separate CSS file, but the fact that 3 out of 4 queries are empty bothers me.

```css
/* small tablet to big tablet [from 768px to 1023 */
@media only screen and (max-width : 1023px) {

}
/* small phone to small tablet [ from 481px to 767px] */
@media only screen and (max-width : 767px) {

}
/* small phon screen [from 0 to 480px] */
@media only screen and (max-width : 480px){
}
```
please either delete those or full them with proper CSS

**Comment by bnazmi** [comment]
@NoureldeanSaed  Thank you for your valuable input .
the issue has been  solved
