### ISSUE TITLE
Team section

### ISSUE THREAD

**Issue by bnazmi** [FACG4/RIAA#3]
this section should contain a short description of about each one of the team [image , Name ]

**Comment by IsraaMoqbel** [comment]
Please, send me your pictures and your personal informations like full names, age, and specialization.
@bnazmi 
@razan99 
@ashatat

**Comment by IsraaMoqbel** [comment]
israamm94@gmail.com

**Comment by IsraaMoqbel** [comment]
Done with this issue!
