### ISSUE TITLE
conventions

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG4/RIAA#30]
ReadMe
fixhedding
horizontalIssu
about-style
all of those are names of your branches
A. If you are not sure of the spelling then google it
B. if you made a mistake naming the branch then it's probably worth correcting it
C. stick to one way of naming your everything, Example: 
readMe, fixHeading, horizontalIssue, aboutStyle
read-me, fix-heading, horizontal-issue, about-style
read_me, fix_heading, horizontal_issue, about_style ...etc

**Comment by ashatat** [comment]
@NoureldeanSaed  Thanks for the tips
