### ISSUE TITLE
dublicate head tag

### ISSUE THREAD

**Issue by reason222life** [FACG4/RIAA#33]
the code consist of duplicate <head> tags, u can remove one and put all it's content in the other one.
and there duplicate <title> tag, and there duplicate meta.

**Comment by reason222life** [comment]
about menu, you used  id, that's good, but you should add unique id for every section with its name in navbar, to enabled move to section by navbar buttons.

**Comment by reason222life** [comment]
there are problem with the responsive.

**Comment by ashatat** [comment]
thanks for the input @reason222life  :+1: 
issues have been resolved
