### ISSUE TITLE
delete unnecessary code

### ISSUE THREAD

**Issue by samarFayez** [FACG4/RIAA#39]
`/* small tablet to big tablet [from 768px to 1023 */
@media only screen and (max-width : 1023px) {

}
/* small phone to small tablet [ from 481px to 767px] */
@media only screen and (max-width : 767px) {

}
/* small phon screen [from 0 to 480px] */
@media only screen and (max-width : 480px){
}`

**Comment by IsraaMoqbel** [comment]
Done, Samar :wink: 
Thanks for your review! :+1:
